server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyenkhoi2202/spring-cloud-config-server.git
          search-paths: demo
          #username:
          #password: